# Generated by Django 5.1.5 on 2025-02-23 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_orders', '0002_remove_order_time_order_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customers',
            options={'verbose_name': 'Customer', 'verbose_name_plural': 'Customers'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-timestamp']},
        ),
    ]
